x-backend-environment: &backend-environment
  APP_NAME: ${APP_NAME:-SendIO}
  APP_KEY: ${APP_KEY}
  APP_DEBUG: ${APP_DEBUG:-false}
  APP_URL: ${APP_URL}
  AUTH_GUARD: ${AUTH_GUARD:-api}
  DB_CONNECTION: ${DB_CONNECTION:-pgsql}
  DB_HOST: ${DB_HOST:-postgres}
  DB_PORT: ${DB_PORT:-5432}
  DB_DATABASE: ${DB_DATABASE}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  MONGO_DB_HOST: ${MONGO_DB_HOST:-mongodb}
  MONGO_DB_PORT: ${MONGO_DB_PORT:-27017}
  MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
  MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
  MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
  REDIS_HOST: ${REDIS_HOST:-redis}
  REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
  REDIS_PORT: ${REDIS_PORT:-6379}
  QUEUE_CONNECTION: ${QUEUE_CONNECTION:-redis}
  JWT_SECRET: ${JWT_SECRET}
  JWT_ALGO: ${JWT_ALGO:-HS256}
  MAIL_MAILER: ${MAIL_MAILER:-smtp}
  MAIL_SCHEME: ${MAIL_SCHEME:-null}
  MAIL_HOST: ${MAIL_HOST}
  MAIL_PORT: ${MAIL_PORT:-2525}
  MAIL_USERNAME: ${MAIL_USERNAME}
  MAIL_PASSWORD: ${MAIL_PASSWORD}
  MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
  MAIL_FROM_NAME: ${MAIL_FROM_NAME:-SendIO}

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *backend-environment
      APP_ENV: production
    expose:
      - "80"
    networks:
      - sendio_net
    depends_on:
      - postgres
      - redis
      - mongodb

  queue-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      <<: *backend-environment
      APP_ENV: production
      QUEUE_CONNECTION: redis
    command: php artisan queue:work redis --sleep=1 --tries=3 --timeout=120
    networks:
      - sendio_net
    depends_on:
      - app
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    networks:
      - sendio_net

  postgres:
    image: 'postgres:18'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sendio-pgsql:/var/lib/postgresql'
    networks:
      - sendio_net

  redis:
    image: 'redis:8.6'
    volumes:
      - 'sendio-redis:/data'
    networks:
      - sendio_net

  mongodb:
    image: 'mongo:8.2'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MONGO_DB_DATABASE}'
    volumes:
      - 'sendio-mongo:/data/db'
      - './config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
    networks:
      - sendio_net

networks:
  sendio_net:
    driver: bridge

volumes:
  sendio-pgsql:
    driver: local
  sendio-redis:
    driver: local
  sendio-mongo:
    driver: local
